apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource-right-sizing.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "resource-right-sizing.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $name, $value := .Values.resource_sizing.secrets }}
  {{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc | quote }}
  {{- end}}
  {{- end }}
